version: "3.9"
services:
  # app:
  #   container_name: app
  #   build:
  #     context: ./fe
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./fe/app:/app:rw
  api:
    container_name: be
    build:
      context: ./be
      dockerfile: ./Dockerfile
    restart: always
    env_file:
    - ./be/app/.env
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./be:/be:rw